### ISSUE TITLE
Project: Website about UN's Sustainable Development Goals

### ISSUE THREAD

**Issue by Rayirth116** [microsoft/hack-together#103]
### Project name

Lamp

### Description

We made a website about the UN's Sustainable Development Goals.
This is made in HTML only

### Repo URL

https://github.com/Rayirth116/Lamp

### Team members

Rayirth Reddy, Raneetha Reddy

**Comment by waldekmastykarz** [comment]
Thank you for your submission @Rayirth116. In this hackathon we're working on apps that are built with .NET and use Microsoft Graph. Since your website doesn't use either technology I'll close this submission.
