### ISSUE TITLE
Project: Booking API sample

### ISSUE THREAD

**Issue by Official-Mwita** [microsoft/hack-together#124]
### Project name

Booking API

### Description

This project is a sample project simulating the booking of a course. The main idea behind this project is to display the usage of recent technologies for software development. Such technologies are:

1. Agile development
2. Using _Sign in with Microsoft_ then utilizing Microsoft Graph information for user registration and login
3.  Using React as a pure front-end application
4. Utilizing Github and Azure app services for continuous development
5. Using dot net core 6 for quick application development
6. Utilizing Microsoft Visual Studio to quicken development
7. Utilizing Azure database and MSQL for rapid database implementations

All thanks to Microsoft for their Amazing technologies

Links: 
React front-end: [Front end website](https://i-business-ui-git-main-moryno.vercel.app/)
Sample API endpoint utilizing login service: [Sample Protected API](https://bookingappmicroservice.azurewebsites.net/) Github: https://github.com/Official-Mwita/bookingapiv6

### Repo URL

https://github.com/Official-Mwita/accountserviceapi

### Team members

https://github.com/jaykaranja, https://github.com/moryno, https://github.com/official-Mwita

**Comment by waldekmastykarz** [comment]
Thank you for your submission @Official-Mwita. It seems that you're not using the Microsoft Graph .NET SDK in your project. Would you be willing to update the project to use the SDK and make a chance to win one of the cool prizes we've got?

**Comment by Official-Mwita** [comment]
yeah sure

**Comment by Official-Mwita** [comment]
how to one set redirect URL  for AuthorizationCodeCredential while using graph. is there any help

**Comment by waldekmastykarz** [comment]
It seems that your project is not using the Microsoft Graph .NET SDK, which is why your hack won't be eligible for prizes. Thank you for your submission and joining us in the hackathon.
