### ISSUE TITLE
Project: AI Assist

### ISSUE THREAD

**Issue by guanryan1234** [microsoft/hack-together#161]
### Project name

AI Assist 

### Description

AI Assist is an open AI based project that integrates various Microsoft Graph endpoints and AI fine fine-tuned models to automate the scheduling of tasks in the Microsoft To-Do app that have to do with creating and scheduling a meeting. In short, AI Assist will auto-complete those specific tasks and add a specific teams meeting to your calendar, along with automating the invite to any user in your particular organization.  

### Repo URL

https://github.com/guanryan1234/Hacktogether-2023

### Team members

Yusuf Corr (YusC3), Ryan Guan (guanryan1234)

**Comment by waldekmastykarz** [comment]
Hey @guanryan1234, it seems like your repo link is invalid (points to a 404 page). Could you please double check it?

**Comment by jkher** [comment]
Hi @guanryan1234,  I was just watching around projects submitted. I think you need to change visibility of your github repo to public. It is not accessible.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility

**Comment by guanryan1234** [comment]
Hi @jkher, good catch, the project visibility has been changed to public.

**Comment by YusC3** [comment]
> Hey @guanryan1234, it seems like your repo link is invalid (points to a 404 page). Could you please double check it?
Is it visible now?

**Comment by YusC3** [comment]
hey @waldekmastykarz we changed the visibility so things should be good?

Also, OpenAI won't let me paste the api key for authenticating into OpenAi. I'll have to regenerate the API Key for OpenAi and send it directly to you via direct message). The Graph Bearer token can be found by navigating to the graph explore and getting   a bearer token (after running a query).

I'll also film a youtube video demonstrating how our app works so you can easily understand. 

Best,
Yusuf Corr

**Comment by YusC3** [comment]
Hey @waldekmastykarz , you can find the youtube video demonstration here: https://www.youtube.com/watch?v=nDvaNtKRdL0.

**Comment by waldekmastykarz** [comment]
Hey @YusC3, thanks I can see the repo now. It seems though, that you're not using the Microsoft Graph .NET SDK. Instead, you're using the HttpClient with a fixed access token to call Microsoft Graph API. As such, unfortunately we can't accept your project to make chance to win hackathon prizes. Thank you for sharing your work with us.

**Comment by YusC3** [comment]
@waldekmastykarz does this disqualify our project or given the general "Judging Criteria" can we still have our application submitted. We worked really hard on this given what we considered to be the requirements. Even if we do not win, I do think this was done with enough quality to make the competition interesting. 

<img width="516" alt="image" src="https://user-images.githubusercontent.com/20896259/225691977-417bf587-8746-4f45-80ca-c62a177c1103.png">

**Comment by waldekmastykarz** [comment]
I really appreciate the effort you put into the hack and it clearly shows that it's not something you put together in a couple of minutes. From our point of view, using the SDK means using it to communicate with the Graph APIs, not just using its types for deserializing data. I'm sorry for this miscommunication. We won't be accepting your submission at this moment.
