### ISSUE TITLE
Authenticate user --- login to the application securely and seamlessly

### ISSUE THREAD

**Issue by bharat1203** [microsoft/hack-together#175]
### Project name

Authentication App

### Description

The Authentication app used to authenticate the user to provide secure login for the application by using the microsoft Identity platform.

the App mainly focuses on authentication of user and fetching the token to perform the events like creating the meeting in calendar.

It restricts the unauthorized access to application and provide the security to information.

### Repo URL

https://github.com/bharat1203/Authenticator-App.git

### Team members

Bharat Kumar Pamarthi

**Comment by vaishnavdev** [comment]
what is this menzz?

**Comment by waldekmastykarz** [comment]
Thank you for your submission @bharat1203. It seems though, that your app is not using Microsoft Graph which is why we can't accept your hack to be eligible for prizes.
