### ISSUE TITLE
Spell Checker with .NET

### ISSUE THREAD

**Issue by Muhammad-Hassaan-Farooq** [microsoft/hack-together#180]
### Project name

DictionaryProjectMSHackTogether

### Description

Using a dictionary to create a spell checker and autocomplete.

### Repo URL

https://github.com/Muhammad-Hassaan-Farooq/DictionaryProjectMSHackTogether

### Team members

Muhammad-Hassaan-Farooq,ShahzaibShoaib,Sickfires94

**Comment by waldekmastykarz** [comment]
Thank you for your submission @Muhammad-Hassaan-Farooq. It seems that your hack is not using Microsoft Graph, which is why we can't accept it to be eligible for prizes.
