### ISSUE TITLE
Desktop App that builds MDE Azure Reporting Solution

### ISSUE THREAD

**Issue by WernerRall147** [microsoft/hack-together#186]
### Project name

MDE Caller using Graph

### Description

We already have an internal Managed IP that runs a Dotnet 6.0 application and then uses Powershell to call Graph API. This is an attempt to convert all that into a single C# Application. 
Currently running exe version has been included. 
The new Graph version is not complete yet...

### Repo URL

https://github.com/WernerRall147/HackTogether

### Team members

Werner Rall

**Comment by waldekmastykarz** [comment]
Hey @WernerRall147, thank you for your submission. While I can see a class that calls Microsoft Graph, I don't see that class being used anywhere. The main form seems to be empty. Since your app isn't working, we can't accept it to participate in the hackathon.

**Comment by WernerRall147** [comment]
Thank you for your feedback. 
This is my v2 of the app. My V1 release did not commit I see... I have added it now, I understand it's a little too late. 
My V1 just wrapped a bunch of ps1 scripts that called the defender apis out of Azure Runbooks: https://api-us.securitycenter.windows.com/api
