### ISSUE TITLE
Project Submission: Learnercord

### ISSUE THREAD

**Issue by thispsj** [microsoft/hack-together#189]
### Project name

Learnercord

### Description

The project is an attendance record management solution integrated right into OneDrive and Microsoft Identity.

I am finalizing the code and it'll be available on the repository soon.

### Repo URL

https://github.com/thispsj/learnercord

### Team members

None except me.

**Comment by waldekmastykarz** [comment]
As the deadline expired and your repo is empty, we can't accept your submission unfortunately.

**Comment by thispsj** [comment]
Ok no problem. @waldekmastykarz 
My bad luck
