### ISSUE TITLE
Project: A console app which displays access token 

### ISSUE THREAD

**Issue by infoadisan** [microsoft/hack-together#191]
### Project name

graphonlytutorial

### Description
based on Grpah tutorial-Build .NET apps with Microsoft Graph and app-only authentication

###Feature
display the access token using graph API

### Repo URL

https://github.com/infoadisan/graph.git

### Team members

sanjeev

**Comment by waldekmastykarz** [comment]
Hey @infoadisan. It seems like your project is not using Microsoft Graph. You are retrieving an access token, but then your app is not using it. Unfortunately, we can't accept your hack to participate in the hackathon. Thank you for sharing your work.

**Comment by infoadisan** [comment]
Thank you sir for your time
