### ISSUE TITLE
Project: Hacktogether project App

### ISSUE THREAD

**Issue by kusscaroline** [microsoft/hack-together#193]
### Project name

Weather Dress Code

### Description

Weather Dress Code App
A Hacktogether project!

This App tells the user about the weather in their location and advises them on how to dress up for the day. 
This was done using: Blazor and Ms Graph API 
Publish on Azure:   weatherdresscode20230313202433.azurewebsites.net

Trouble - with the Ms login - got in before, but today, just won't allow me -goes round and round...-what a maze and a time waster!
 https://login.microsoftonline.com/common/login.

Anyway, I hope you would be able to see it and thank you for the opportunity - was a good try!

### Repo URL

https://github.com/kusscaroline/WeatherDressCode

### Team members

Caroline Manta

**Comment by waldekmastykarz** [comment]
Hey @kusscaroline. It seems like your repo is inaccessible. Could you please double check the URL and the visibility? Otherwise, we won't be able to judge your hack.

**Comment by waldekmastykarz** [comment]
As the deadline passed, we'll close your submission.

**Comment by kusscaroline** [comment]
Hi,
Sorry, I have just seen this message. I have been looking into the problem; it says that the App's hosting domain has not been verified. On the other hand the test account which I had used to accessed Microsoft Graph has locked me out, and I am still struggling to rectify this issue?

**Comment by waldekmastykarz** [comment]
Sorry to hear you're running into trouble. I don't know anything of the top of my head that could be causing the issue you're seeing 🙁

**Comment by kusscaroline** [comment]
However, my other test App -still has access-
https://blazorsample20230311185652.azurewebsites.net/

**Comment by kusscaroline** [comment]
Both Apps are in the 365 Apps Manager

**Comment by kusscaroline** [comment]
Praise the Lord, my to God!
I have finally figured out the problems:
First of all - I had chosen a multi-tenant settings, hence it enforces a need to verify.
Second - Since I was using the Ms365 toolkit, everything automated and set on rock (in the Azure Manifest)
Third - Ms Identity platform messed up my user accounts and uploaded the App using a different logging from the one (test) I had set up on Ms 365, the tenant was different and so, once I had tried a few times to log on, it seemed to locked out the account. Although, I can get in now, Azure is holding that App ransom and I cannot modify it.

Here is a test run with a new test app - working.
https://blazorapp320230316224804.azurewebsites.net

Please, kindly consider it that I had submitted my App on time, except for those issues that were not in my control.
Regards
Caroline
