### ISSUE TITLE
Project: This is a sample app that get user info using the Microsoft GraphApi

### ISSUE THREAD

**Issue by William-Mba** [microsoft/hack-together#206]
### Project name

GraphApi Hackathon App

### Description

From` app.module.ts`, use your own `clientId` and `authority` URI

### Repo URL

https://github.com/William-Mba/GraphApi-hackathon-app

### Team members

https://github.com/William-Mba/

**Comment by waldekmastykarz** [comment]
Hey @William-Mba, it seems that the project you submitted is not build using .NET and the Microsoft Graph .NET SDK. As such, we can't accept it to be eligible for hackathon prizes. Nonetheless, thank you for sharing your work.
