### ISSUE TITLE
Project: Automation in Hazardous Jobs

### ISSUE THREAD

**Issue by Snehagavande** [microsoft/hack-together#207]
### Project name

Automation in hazardous jobs

### Description

Automation in Hazardous Jobs

In 2017, there were 1.6 million fires in India, resulting in over 27,000 fire-related deaths. (Source: Global Diseases Burden) As a result, India accounts for one-fifth of all fire-related deaths worldwide.

The high incidence of fire-related deaths in India is due to a lack of suitable fire stations and firemen. It's a dangerous career, and every time a firefighter saves a life, he/she risks his own. You can propose a solution to this problem through this initiative. Here you may build an autonomous robot that can travel through confined locations and calculate a course quickly. The robot learns and adapts to a variety of situations with the help of [Deep learning](https://www.careers360.com/courses-certifications/deep-learning-courses-brpg) . Thus this is one of the best hackathon ideas for beginners if you are interested in automation.

### Repo URL

https://sneha18//github.com

### Team members

Sneha gavande

**Comment by waldekmastykarz** [comment]
Hey @Snehagavande. I'm afraid you submitted an invalid URL. Could you please double check it?

**Comment by waldekmastykarz** [comment]
As the deadline passed, we'll close your submission.

**Comment by Snehagavande** [comment]
no i havent

**Comment by Snehagavande** [comment]
HACK.PROJECT.pptx
<https://1drv.ms/p/s!AuNMtEjxAns_gQpFYBenRALwSV5B?e=XDO5eJ>
