### ISSUE TITLE
Project: AVD Session Manager

### ISSUE THREAD

**Issue by cscaminaci** [microsoft/hack-together#39]
### Project name

AVD Session Manager

### Description

AVD Session Manager is a Blazor server application built on Mudblazor and the Azure .NET SDK to more easily control user sessions in Azure Virtual Desktop. This is a sanitized version of my in house production tooling for Microsoft Hack Together 2023.

This app is designed to be CSP/MSP friendly, meaning it authenticates the user to the CSP tenant, and then uses an app registration in the target tenant to interact with AVD. Eventually, this app will allow multitenant management of AVD for MSPs from one central app instead of market alternatives like Nerdio that require an appservice to be stood up in each tenant you manage.

### Repo URL

https://github.com/cscaminaci/AVD-Session-Manager

### Team members

cscaminaci, mspautomator (me but public repo)

**Comment by waldekmastykarz** [comment]
Thank you for submitting your hack @cscaminaci. It doesn't seem though like it's using Microsoft Graph and the Microsoft Graph .NET SDK, which are both prerequisites for this hackathon. Are you planning to extend it with Microsoft Graph?
