### ISSUE TITLE
🎉 Let's get to know each other!

### ISSUE THREAD

**Issue by ta-chi-na** [microsoft/hack-together#40]
HI FRIENDS!! My name is Tachina. I am a student learning code all around the world. I can't wait to learn new hacks during this period! You all inspire me to learn every day and strengthen my code. Good luck to you all and keep learning/educating. ☮️

**Comment by ta-chi-na** [comment]
I was trying to leave a comment in the discussion and ended up here. Instead of posting a comment, I created an issue. I find it challenging that the comment section is at the bottom of the discussion. 

What do you think?

**Comment by Jackofmn12** [comment]
I don't think much
