### ISSUE TITLE
Thanks for the suggestion!

### ISSUE THREAD

**Issue by Jackofmn12** [microsoft/hack-together#42]
Thanks for the suggestion!

How do you think CLI should warn about this: by printing a message to stderr and proceeding immediately, or by requiring you to confirm a potentially dangerous action?

_Originally posted by @mislav in https://github.com/cli/cli/issues/6598#issuecomment-1313577402_

**Comment by waldekmastykarz** [comment]
It seems like you posted this issue here by accident. I'll close it
