### ISSUE TITLE
Project: CSPLicenseInquiry

### ISSUE THREAD

**Issue by cscaminaci** [microsoft/hack-together#43]
### Project name

CSPLicenseInquiry

### Description

License inquiry and report script for HaloPSA using Microsoft Graph for Hack Together 2023.

This tool runs as an Azure Runbook and is triggered via webhook from HaloPSA. The script uses a multitenant app registration to look up current user license assignments and attempts to find zombie accounts or accounts that are licensed but deactivated or deleted. This helps to scavenge available licenses during the onboarding process. The report is returned to HaloPSA as an HTML fragment embedded in a private note.

### Repo URL

https://github.com/cscaminaci/CSPLicenseInquiry

### Team members

cscaminaci

**Comment by waldekmastykarz** [comment]
Thank you for the submission. It seems though that the script is a PowerShell script that uses Microsoft Graph PowerShell SDK rather than .NET. This hackathon is all about using Microsoft Graph with .NET.

**Comment by cscaminaci** [comment]
Someone asked you guys about Powershell on the stream yesterday and you said to submit Powershell stuff also. How is Powershell not related to .NET when it's leveraging the same .NET libraries with only slightly different syntax?

**Comment by waldekmastykarz** [comment]
The question we got was about using the Microsoft Graph .NET SDK in a PowerShell script.

**Comment by waldekmastykarz** [comment]
Hey @cscaminaci, just wanted to check if you're planning to convert your hack to use the Microsoft Graph .NET SDK and make chance for some of the cool prizes we've got.

**Comment by waldekmastykarz** [comment]
Unfortunately, we can't accept your hack to be eligible for prizes because it's not using the Microsoft Graph .NET SDK. Thank you for your submission.
