### ISSUE TITLE
Project: SMS Identity Verification

### ISSUE THREAD

**Issue by mspautomator** [microsoft/hack-together#44]
### Project name

SMS Identity Verifier

### Description

This tool was originally featured on my blog here: https://mspautomator.com/2022/08/27/one-click-user-identity-verification-from-halopsa/

How do you know that person calling your helpdesk is who they say they are? Social engineering a helpdesk employee is a highly effective method of bypassing physical and logical access controls to breach an environment. This is a big enough problem in single silo organizations that have internal IT teams, but it presents a much larger attack surface for an MSP. You can’t “know” every one of your thousands of end users at clients, and that’s especially true for new employees joining your helpdesk team and starting from zero. Today we’re going to take a look at a creative way to make your own user identity verification system that avoids some of the pitfalls of commercially available products and harnesses Twilio, Microsoft Graph, and Azure Automation runbooks all from one click inside HaloPSA.

### Repo URL

https://github.com/mspautomator/SMSIdentityVerification

### Team members

mspautomator, cscaminaci

**Comment by waldekmastykarz** [comment]
Thank you for your submission. This script seems to be a PowerShell script that uses the Microsoft Graph PowerShell SDK. This hackathon is all about using Microsoft Graph with .NET.

**Comment by waldekmastykarz** [comment]
Hey @mspautomator, are you planning to update the hack to use the Microsoft Graph .NET SDK and make chance for one of the cool prizes we've got in the hackathon?

**Comment by waldekmastykarz** [comment]
Unfortunately, we can't accept your hack to be eligible for prizes because it's not using the Microsoft Graph .NET SDK. Thank you for your submission.
