### ISSUE TITLE
Project:  Analyse, Estimate and Connect for health related issues

### ISSUE THREAD

**Issue by vishalbhatd123456** [microsoft/hack-together#48]
### Project name

EstimateCostForDiseases

### Description

In today's world, the cost of prescription, various medical commodities have been increasingly high and sometimes it is not possible for the common man to afford. While there are many non-profit orgs, we would like to track and dig deeper and help to get the least cost diagnosis for anyone aspiring for.

Analyze the current costs for various diseases, surgeries that are being charged today as a part of all the orgs (government / private) hospitals.
Using MicrosoftGraph to compute the least cost locale (hospital) for a person with the particular issue.
Use Graph if possible to connect the patient in emergency (atleast the phone number) to a doctor who can immediately consult
Make an ML model to analyze the stroke deaths that have happened within seconds and try to come up with an approach that will prevent the same / give a solution for the same.
Use Azure, Graph and try making a GPT that resembles the ChatGPT but this time for the health care industry called HealthGPT / DoctorGPT.

### Repo URL

https://github.com/vishalbhatd123456/vishalbhatd123456-EstimateCostForDiseases

### Team members

vishalbhatd123456, Saurabh7379

**Comment by waldekmastykarz** [comment]
Very interesting idea! Thank you for sharing and we're looking forward to seeing your hack!

**Comment by waldekmastykarz** [comment]
Seems like your repo is empty. We'll close this submission. Thank you for joining us in the hackathon!
