### ISSUE TITLE
Project: import epub to onenote

### ISSUE THREAD

**Issue by lostsquirrel** [microsoft/hack-together#71]
### Project name

onenote-converter

### Description

import epub to onenote as a new notebootk, each page as a page in notebook

### Repo URL

https://github.com/lostsquirrel/onenote-converter

### Team members

lostsquirrel

**Comment by waldekmastykarz** [comment]
Hey @lostsquirrel. Thank you for your submission. In this hackathon we're building apps using .NET and the Microsoft Graph .NET SDK. It seems like your project is built using Python. Would you be willing to convert your project to .NET to participate in the hackathon and make chance for one of prizes?

**Comment by lostsquirrel** [comment]
sorry, I am not familiar with .NET developing, I'll close it
