### ISSUE TITLE
Project: Azure guest users cleanup

### ISSUE THREAD

**Issue by dmasuw** [microsoft/hack-together#77]
### Project name

Azure guest users cleanup

### Description

getting the stats about guest accounts (accounts not accepted the invite,  ect.) and potentially delete with some accounts if it follows certain criteria. 

### Repo URL

https://github.com/dmasuw/MSGraph

### Team members

dmasuw

**Comment by waldekmastykarz** [comment]
Seems like your repo is empty. We'll close this submission. Thank you for joining us in the hackathon!
